### PR TITLE
Minor speeling updates

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by victorlin** [comment]
@asottile thanks :P 

pre-commit looks awesome, I just enabled on this project

**Comment by asottile** [comment]
@victorlin great to hear it! Let me know if you have any issues with it :)

**Comment by victorlin** [comment]
@asottile I actually did similar thing 😀

http://victorlin.me/posts/2014/02/05/auto-post-commit-pep8-correction

it's so great to have an awesome tool for this

**Comment by victorlin** [comment]
@asottile 

by the way

```
$ pre-commit install
An unexpected error has occurred: IOError: [Errno 2] No such file or directory: '/Users/victorlin/workspace/bugbuzz/bugbuzz-api/.git/hooks/pre-commit'
```

I have to create `hooks` folder manually

```
mkdir .git/hooks
```

is this a bug?

**Comment by asottile** [comment]
Probably!  What version of git are you using?  I'll make a quick fix for it

**Comment by victorlin** [comment]
@asottile `git version 2.3.2 (Apple Git-55)`

**Comment by asottile** [comment]
Awesome, created https://github.com/pre-commit/pre-commit/issues/234 to track it and I'm making a quick fix now :)

**Comment by victorlin** [comment]
😎👍

**Comment by asottile** [comment]
The fix should be available in version 0.5.1

**Pull request merged**
